apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl # name of the deployment
spec: # how deployment should behave
  replicas: 1 # number of pods
  selector:
    matchLabels: # lavel -> key and value, in this exampl key is app and value is posts
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: rpate467/client
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
