apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl # name of the deployment
spec: # how deployment should behave
  replicas: 1 # number of pods
  selector:
    matchLabels: # lavel -> key and value, in this exampl key is app and value is posts
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: rpate467/comments
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  type: ClusterIP
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
