apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl # name of the deployment
spec: # how deployment should behave
  replicas: 1 # number of pods
  selector:
    matchLabels: # lavel -> key and value, in this exampl key is app and value is posts
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: rpate467/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000