apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl # name of the deployment
spec: # how deployment should behave
  replicas: 1 # number of pods
  selector:
    matchLabels: # lavel -> key and value, in this exampl key is app and value is posts
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: rpate467/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
